name: DS918

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: false
        type: boolean
  push:
    branches:
      - master
    paths:
      - "docker/**"
      - "**.sh"
      - "**.json"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Chmod
        run: chmod 0755 ./redpill_tool_chain.sh

      - name: Build docker image
        run: ./redpill_tool_chain.sh build ds918p-7.1.0-42661

      - name: Create dsm image
        run: ./redpill_tool_chain.sh auto ds918p-7.1.0-42661

      - uses: actions/upload-artifact@v3
        with:
          name: dsm918
          path: ./images
